name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Determine changed test files
      id: changed_files
      run: |
        echo "Changed files:"
        git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed_files.txt
        cat changed_files.txt

    - name: Run tests based on changed test files
      run: |
        for file in $(cat changed_files.txt); do
          if [[ "$file" == test_*.py ]]; then
            echo "Running tests in $file"
            pytest $file
          fi
        done

    - name: Linting
      run: flake8  # Run code linting

